name: Terraform Apply

on:
  push:
    branches: [ master ]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    env:
      tf-bootstrap: ./terraform/bootstrap
      tf-postbootstrap: ./terraform/postbootstrap
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "1.2.2"
      run: |
        tf_version=$TERRAFORM_VERSION
        curl -O https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip -o terraform_"$tf_version"_linux_amd64.zip
        chmod +x terraform
        sudo mv terraform /usr/local/bin/

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ${{env.tf-bootstrap}}
      run: terraform init -input=false

    - name: Terraform validation
      working-directory: ${{env.tf-bootstrap}}
      run: terraform validate

    - name: Terraform apply
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: ${{env.tf-bootstrap}}
      run: terraform apply -auto-approve -input=false
